version: "3.8"

services:
  app:
    build: ./
    command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: development
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
